# Skills Exercise Week 6
---
**Author:** Jay Ballesteros
**Due date:** May 1st, 2026

## 1.1 File Setup

Create a Jupyter Notebook for your skills assignment, with a file extension of .ipynb
- Make the first cell a markdown cell, and put in the name of the assignment, your name, and the due date.
- The second cell should be your imports for the assignment. In this case, pandas, matplotlib, and os. Do not put imports anywhere else in your assignment!

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight') #https://matplotlib.org/stable/gallery/style_sheets/fivethirtyeight.html

## 2.1 Loading Data

Load the Diamonds data from the diamonds.csv file (available on Canvas) into a Pandas DataFrame with a descriptive name (e.g., df diamonds)

In [2]:
PATH = ("/Users/jayballesteros/_github/uchicago-mpp/3_spring_2026/data_programming/skills-psets/_data")
print(PATH)

df_diamonds = pd.read_csv(os.path.join(PATH, "diamonds.csv"))

/Users/jayballesteros/_github/uchicago-mpp/3_spring_2026/data_programming/skills-psets/_data

## 2.2 Exploratory Data Analysis: 
Show code of your basic exploration of the data, and answer the following:

### How many rows and columns does the data have?
Running the `df_diamonds.shape` I get 53940 rows and 10 columns

In [3]:
df_diamonds.shape

(53940, 10)

### Do any of the rows or columns have missing values?
None. By implementing `df_diamonds.isna().sum()`I get 0 missing values for all 10 existing columns

In [4]:
df_diamonds.isna().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

#### Which columns are non-numeric, and what are the unique values in each?
Mapping with `df_diamonds.dtypes` I got that the only non-numeric columns are `cut`, `color` and `clarity`. The three of them are an object.
The unique values for this columns are:
| Columns | Unique values |
|:--------------------|:--------------|
| `cut`               | ['Ideal' 'Premium' 'Good' 'Very Good' 'Fair'] |
| `color`             | ['E' 'I' 'J' 'H' 'F' 'G' 'D'] |
| `clarity`           | ['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF'] |

In [5]:
df_diamonds.dtypes

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object

In [6]:
print(df_diamonds["cut"].unique())
print(df_diamonds["color"].unique())
print(df_diamonds["clarity"].unique())

['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
['E' 'I' 'J' 'H' 'F' 'G' 'D']
['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF']

### What does each row of the data represent?
If I have to take I guess, I'll say that each row is a specific diamond.

In [7]:
df_diamonds.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

## 2.3 Price Within Groups: There are eight different values for the “clarity” column.

### First, calculate the mean price for all of the observations.
Mean `price` is 3932.8

In [8]:
print(df_diamonds["price"].mean().round(2))

3932.8

### Next, calculate the mean price for each of the clarity groups. As we were last week, write a for-loop with subsetting to report the eight different mean values in print functions.

In [9]:


clarity = ['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']

for clar in clarity:
    clarity_filter = df_diamonds.loc[df_diamonds["clarity"] == clar]
    calculated_means = clarity_filter["price"].mean()
    print(f"Clarity: {clar}, {round(calculated_means, 2)}")

Clarity: SI2, 5063.03
Clarity: SI1, 3996.0
Clarity: VS1, 3839.46
Clarity: VS2, 3924.99
Clarity: VVS2, 3283.74
Clarity: VVS1, 2523.11
Clarity: I1, 3924.17
Clarity: IF, 2864.84

### Now that we know how to use groupby, we have an easier way! Report the same eight mean values using a single groupby operation.

In [10]:
df_diamonds.groupby("clarity")["price"].mean().round(2)

clarity
I1      3924.17
IF      2864.84
SI1     3996.00
SI2     5063.03
VS1     3839.46
VS2     3924.99
VVS1    2523.11
VVS2    3283.74
Name: price, dtype: float64

## 2.4 Custom Sorting Order: It is hard to interpret the mean values across the clarity groups, because it isn’t obvious to someone untrained in grading diamonds which clarity is better than another.

### First, create a new DataFrame equal to the result of grouping by clarity and showing the mean value for all numeric columns (it should have 8 rows and 8 columns, or 7 if you leave clarity in the index)

In [11]:
df_diamonds.groupby("clarity")["price"].mean().round(2)

clarity
I1      3924.17
IF      2864.84
SI1     3996.00
SI2     5063.03
VS1     3839.46
VS2     3924.99
VVS1    2523.11
VVS2    3283.74
Name: price, dtype: float64

In [12]:
df_diamonds.groupby("clarity")["price"].mean().round(2)

clarity
I1      3924.17
IF      2864.84
SI1     3996.00
SI2     5063.03
VS1     3839.46
VS2     3924.99
VVS1    2523.11
VVS2    3283.74
Name: price, dtype: float64

In [13]:
df_diamonds.dtypes

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object

In [14]:
calc_means = {'carat':'mean', 'depth':'mean', 'table':'mean', 'price':'mean', 'x':'mean', 'y':'mean', 'z':'mean'} # https://stackoverflow.com/questions/47360510/pandas-groupby-and-aggregation-output-should-include-all-the-original-columns-i

df_gmeans = df_diamonds.groupby(['clarity'], as_index=False).agg(calc_means).round(2)

print(df_gmeans)

  clarity  carat  depth  table    price     x     y     z
0      I1   1.28  62.73  58.30  3924.17  6.76  6.71  4.21
1      IF   0.51  61.51  56.51  2864.84  4.97  4.99  3.06
2     SI1   0.85  61.85  57.66  3996.00  5.89  5.89  3.64
3     SI2   1.08  61.77  57.93  5063.03  6.40  6.40  3.95
4     VS1   0.73  61.67  57.32  3839.46  5.57  5.58  3.44
5     VS2   0.76  61.72  57.42  3924.99  5.66  5.66  3.49
6    VVS1   0.50  61.62  56.88  2523.11  4.96  4.98  3.06
7    VVS2   0.60  61.66  57.02  3283.74  5.22  5.23  3.22

### Sort the values in descending order of clarity. How did this sort the data, and was it helpful?

Not really. Order looks weird since it seems to be considering alphabetical order. Therefore, maybe it would be more valuable if is organized by quantitative information. For instance, price.

In [15]:
df_gmeans.sort_values(by="clarity", ascending=False)

  clarity  carat  depth  table    price     x     y     z
7    VVS2   0.60  61.66  57.02  3283.74  5.22  5.23  3.22
6    VVS1   0.50  61.62  56.88  2523.11  4.96  4.98  3.06
5     VS2   0.76  61.72  57.42  3924.99  5.66  5.66  3.49
4     VS1   0.73  61.67  57.32  3839.46  5.57  5.58  3.44
3     SI2   1.08  61.77  57.93  5063.03  6.40  6.40  3.95
2     SI1   0.85  61.85  57.66  3996.00  5.89  5.89  3.64
1      IF   0.51  61.51  56.51  2864.84  4.97  4.99  3.06
0      I1   1.28  62.73  58.30  3924.17  6.76  6.71  4.21

### The correct order from worst to best is: I3, I2, I1, SI2, SI1, VS2, VS1, VVS2, VVS1, IF, FL. Look up in the official documentation how to create a custom sorting order using the pd.Categorical class, and apply it to the clarity column. You should do this on the full data, then redo your creation of df clarity. Then redo your sorting so that sort values puts your data in a meaningful order.

In [16]:
#  unique values of clarity ['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF']. adding FL, I2 and I3 was messsing with 2.4 

order = ["I1", "SI2", "SI1", "VS2", "VS1", "VVS2", "VVS1", "IF"]

df_diamonds["clarity"] = pd.Categorical(df_diamonds["clarity"], order) #https://stackoverflow.com/questions/13838405/custom-sorting-in-pandas-dataframe

df_diamonds = df_diamonds.sort_values("clarity")

calc_means = {'carat':'mean', 'depth':'mean', 'table':'mean', 'price':'mean', 'x':'mean', 'y':'mean', 'z':'mean'}

df_gmeans = df_diamonds.groupby(['clarity'], as_index=False).agg(calc_means).round(2)

print(df_gmeans)

  clarity  carat  depth  table    price     x     y     z
0      I1   1.28  62.73  58.30  3924.17  6.76  6.71  4.21
1     SI2   1.08  61.77  57.93  5063.03  6.40  6.40  3.95
2     SI1   0.85  61.85  57.66  3996.00  5.89  5.89  3.64
3     VS2   0.76  61.72  57.42  3924.99  5.66  5.66  3.49
4     VS1   0.73  61.67  57.32  3839.46  5.57  5.58  3.44
5    VVS2   0.60  61.66  57.02  3283.74  5.22  5.23  3.22
6    VVS1   0.50  61.62  56.88  2523.11  4.96  4.98  3.06
7      IF   0.51  61.51  56.51  2864.84  4.97  4.99  3.06

/var/folders/8p/mzh9p8r52s795vp2hwtly6t40000gn/T/ipykernel_77465/1009602307.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_gmeans = df_diamonds.groupby(['clarity'], as_index=False).agg(calc_means).round(2)

## 2.5. Solving the Price Mystery: The best category of clarity (in our dataset), IF, does not have the highest average price. In fact, we have to go all the way to SI2 for the highest average price, and this may be particularly puzzling, because the SI2 clarity group doesn’t even have the highest average value of carat (weight)!

### We can’t use groupby on a continuous variable directly, so instead we will split carat into two categories. Using the map method and an anonymous function on the full data (not the clarity subset), create a dummy variable that is equal to 1 if “carat” is greater than 1, else 0 if “carat” is equal to or less than 1. Assign this to a new column named “>1ct”.

In [17]:
df_diamonds[">1ct"] = df_diamonds["carat"].map(lambda x: 1 if x > 1 else 0) # https://stackoverflow.com/questions/29247718/map-an-if-statement-in-python

### Create a new DataFrame named counts that is equal to the number of observations in each group, when grouping by both “clarity” and “>1ct”. Its shape should be (16, 9) if you leave the grouping keys in the index.

In [ ]:
counts = df_diamonds.groupby(["clarity", ">1ct"]).count()

In [21]:
print(counts.shape)

(16, 9)

In [20]:
print(counts)

              carat   cut  color  depth  table  price     x     y     z
clarity >1ct
I1      0       248   248    248    248    248    248   248   248   248
        1       493   493    493    493    493    493   493   493   493
SI2     0      4297  4297   4297   4297   4297   4297  4297  4297  4297
        1      4897  4897   4897   4897   4897   4897  4897  4897  4897
SI1     0      8483  8483   8483   8483   8483   8483  8483  8483  8483
        1      4582  4582   4582   4582   4582   4582  4582  4582  4582
VS2     0      8575  8575   8575   8575   8575   8575  8575  8575  8575
        1      3683  3683   3683   3683   3683   3683  3683  3683  3683
VS1     0      5935  5935   5935   5935   5935   5935  5935  5935  5935
        1      2236  2236   2236   2236   2236   2236  2236  2236  2236
VVS2    0      4090  4090   4090   4090   4090   4090  4090  4090  4090
        1       976   976    976    976    976    976   976   976   976
VVS1    0      3259  3259   3259   3259   3259   3259  3259  3259  3259
        1       396   396    396    396    396    396   396   396   396
IF      0      1551  1551   1551   1551   1551   1551  1551  1551  1551
        1       239   239    239    239    239    239   239   239   239

In [22]:
counts

              carat   cut  color  depth  table  price     x     y     z
clarity >1ct
I1      0       248   248    248    248    248    248   248   248   248
        1       493   493    493    493    493    493   493   493   493
SI2     0      4297  4297   4297   4297   4297   4297  4297  4297  4297
        1      4897  4897   4897   4897   4897   4897  4897  4897  4897
SI1     0      8483  8483   8483   8483   8483   8483  8483  8483  8483
        1      4582  4582   4582   4582   4582   4582  4582  4582  4582
VS2     0      8575  8575   8575   8575   8575   8575  8575  8575  8575
        1      3683  3683   3683   3683   3683   3683  3683  3683  3683
VS1     0      5935  5935   5935   5935   5935   5935  5935  5935  5935
        1      2236  2236   2236   2236   2236   2236  2236  2236  2236
VVS2    0      4090  4090   4090   4090   4090   4090  4090  4090  4090
        1       976   976    976    976    976    976   976   976   976
VVS1    0      3259  3259   3259   3259   3259   3259  3259  3259  3259
        1       396   396    396    396    396    396   396   396   396
IF      0      1551  1551   1551   1551   1551   1551  1551  1551  1551
        1       239   239    239    239    239    239   239   239   239

### Now note that the columns in counts are redundant, since the number of observations in each is the same. Filter the counts DataFrame to a single column (besides the grouping keys), and rename that column to “counts”.

In [24]:
counts = counts[["carat"]].rename(columns={"carat": "counts"})

In [25]:
counts

              counts
clarity >1ct
I1      0        248
        1        493
SI2     0       4297
        1       4897
SI1     0       8483
        1       4582
VS2     0       8575
        1       3683
VS1     0       5935
        1       2236
VVS2    0       4090
        1        976
VVS1    0       3259
        1        396
IF      0       1551
        1        239

### Next make another DataFrame named “df cl wgt” that is equal to the the original data grouped by both “clarity” and “>1ct”, aggregated by mean values.

In [ ]:
df_cl_wgt = df_diamonds.groupby(["clarity", ">1ct"], as_index=False).agg(calc_means).round(2)

/var/folders/8p/mzh9p8r52s795vp2hwtly6t40000gn/T/ipykernel_77465/9813610.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_cl_wgt = df_diamonds.groupby(["clarity", ">1ct"], as_index=False).agg(calc_means).round(2)

In [29]:
df_cl_wgt

   clarity  >1ct  carat  depth  table     price     x     y     z
0       I1     0   0.76  62.99  58.55   1589.33  5.76  5.69  3.61
1       I1     1   1.55  62.61  58.18   5098.69  7.26  7.22  4.51
2      SI2     0   0.68  61.80  57.72   2126.23  5.55  5.55  3.43
3      SI2     1   1.43  61.75  58.11   7640.00  7.15  7.15  4.41
4      SI1     0   0.59  61.87  57.53   1910.55  5.28  5.29  3.27
5      SI1     1   1.34  61.82  57.91   7856.96  7.01  7.00  4.33
6      VS2     0   0.52  61.72  57.26   1762.33  5.08  5.08  3.14
7      VS2     1   1.33  61.73  57.79   8960.23  7.01  7.00  4.32
8      VS1     0   0.51  61.68  57.19   1759.92  5.04  5.05  3.12
9      VS1     1   1.31  61.64  57.64   9359.16  6.99  6.98  4.30
10    VVS2     0   0.45  61.66  56.98   1629.85  4.83  4.85  2.98
11    VVS2     1   1.22  61.69  57.21  10214.46  6.84  6.85  4.22
12    VVS1     0   0.42  61.63  56.84   1489.23  4.73  4.75  2.92
13    VVS1     1   1.22  61.55  57.24  11031.82  6.83  6.84  4.20
14      IF     0   0.40  61.52  56.35   1482.02  4.69  4.71  2.89
15      IF     1   1.20  61.43  57.51  11838.72  6.81  6.83  4.19

### Assign the DataFrame you named counts to a column in this new data named “counts”

In [30]:
df_cl_wgt["counts"] = counts["counts"]

TypeError: incompatible index of inserted column with frame index

In [ ]:
df_cl_wgt

### Look at just the grouping keys (“clarity” and “>1ct”) and the “price” and “counts” columns. Which group has the largest price now?

### Create a new column in “df cl wgt” named “avg unit price” and set it equal to the “price” column divided by the “carat” column. Which three groups have the highest price per unit of carat weight? Which group has the highest average carat weight?